# Generated by Django 5.2.5 on 2025-08-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("startup", "1-10 employees"),
                            ("small", "11-50 employees"),
                            ("medium", "51-200 employees"),
                            ("large", "201-1000 employees"),
                            ("enterprise", "1000+ employees"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=255)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scrape_interval",
                    models.PositiveIntegerField(
                        default=3600, help_text="Scraping interval in seconds"
                    ),
                ),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("total_jobs_scraped", models.PositiveIntegerField(default=0)),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=1, help_text="Delay between requests in seconds"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Custom user agent for scraping",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
