# Generated by Django 5.2.5 on 2025-08-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "external_id",
                    models.CharField(
                        help_text="Job ID from the source website", max_length=255
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "remote_type",
                    models.CharField(
                        choices=[
                            ("fully_remote", "Fully Remote"),
                            ("hybrid", "Hybrid"),
                            ("on_site", "On-site"),
                        ],
                        default="on_site",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("principal", "Principal"),
                            ("director", "Director"),
                        ],
                        max_length=20,
                    ),
                ),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                ("posted_date", models.DateTimeField()),
                ("scraped_date", models.DateTimeField(auto_now_add=True)),
                ("expires_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("skills_required", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.jobsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="JobBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job")},
            },
        ),
        migrations.AddField(
            model_name="job",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_jobs",
                through="jobs.JobBookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["company"], name="jobs_job_company_9ee5ea_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["source"], name="jobs_job_source__8bc5d9_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["posted_date"], name="jobs_job_posted__0a7770_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active"], name="jobs_job_is_acti_b6ae73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_remote"], name="jobs_job_is_remo_78fc35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_type"], name="jobs_job_job_typ_f6c220_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("source", "external_id")},
        ),
    ]
