# Generated by Django 5.2.5 on 2025-08-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("job_types", models.JSONField(default=list)),
                ("remote_only", models.BooleanField(default=False)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("company_sizes", models.JSONField(default=list)),
                ("experience_levels", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never (Save Only)"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("jobs_found_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_title", models.CharField(blank=True, max_length=255)),
                (
                    "career_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("junior", "Junior (2-4 years)"),
                            ("mid", "Mid Level (4-7 years)"),
                            ("senior", "Senior (7-10 years)"),
                            ("lead", "Lead (10+ years)"),
                            ("principal", "Principal/Staff (12+ years)"),
                            ("director", "Director/VP (15+ years)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "desired_salary_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "desired_salary_max",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                (
                    "preferred_job_types",
                    models.JSONField(
                        default=list,
                        help_text="List of preferred job types: full_time, part_time, contract, etc.",
                    ),
                ),
                (
                    "preferred_remote_type",
                    models.CharField(
                        choices=[
                            ("fully_remote", "Fully Remote Only"),
                            ("hybrid", "Hybrid/Flexible"),
                            ("on_site", "On-site Only"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("willing_to_relocate", models.BooleanField(default=False)),
                (
                    "preferred_locations",
                    models.JSONField(
                        default=list, help_text="List of preferred work locations"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="List of technical skills"
                    ),
                ),
                (
                    "industries_of_interest",
                    models.JSONField(
                        default=list, help_text="Industries the user is interested in"
                    ),
                ),
                (
                    "company_sizes_preferred",
                    models.JSONField(
                        default=list,
                        help_text="Preferred company sizes: startup, small, medium, large, enterprise",
                    ),
                ),
                ("is_actively_searching", models.BooleanField(default=True)),
                ("is_open_to_opportunities", models.BooleanField(default=False)),
                (
                    "job_search_status",
                    models.CharField(
                        choices=[
                            ("active", "Actively Searching"),
                            ("passive", "Open to Opportunities"),
                            ("not_looking", "Not Looking"),
                            ("employed", "Recently Employed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("daily_job_digest", models.BooleanField(default=False)),
                ("weekly_summary", models.BooleanField(default=True)),
                ("application_reminders", models.BooleanField(default=True)),
                (
                    "current_resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/%Y/%m/"),
                ),
                ("resume_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
