# Generated by Django 5.2.5 on 2025-08-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("applied", "Applied"),
                            ("screening", "Phone/Video Screening"),
                            ("interview", "Interview"),
                            ("technical", "Technical Assessment"),
                            ("final", "Final Interview"),
                            ("offer", "Offer Received"),
                            ("accepted", "Offer Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("ghosted", "No Response"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("dream", "Dream Job"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("interview_date", models.DateTimeField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("cover_letter", models.TextField(blank=True)),
                ("resume_version", models.CharField(blank=True, max_length=100)),
                ("portfolio_link", models.URLField(blank=True)),
                ("recruiter_name", models.CharField(blank=True, max_length=255)),
                ("recruiter_email", models.EmailField(blank=True, max_length=254)),
                ("hiring_manager_name", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "application_method",
                    models.CharField(
                        choices=[
                            ("website", "Company Website"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("referral", "Referral"),
                            ("job_board", "Job Board"),
                            ("recruiter", "Recruiter"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                ("salary_offered", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                ("benefits_offered", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this application"
                    ),
                ),
                ("interview_feedback", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("portfolio", "Portfolio"),
                            ("transcript", "Transcript"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="application_documents/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("is_important", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_notes",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "status"], name="application_user_id_55b4e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applied_date"], name="application_applied_37965e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["follow_up_date"], name="application_follow__d762a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "job")},
        ),
    ]
